/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AgcCornHarvestLossInputs {
    'socket': string;
  }
  interface AgcCornHarvestLossInputsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcCornHarvestLossProgress {
    'socket': string;
  }
  interface AgcCornHarvestLossProgressAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcCornHarvestLossResultsPlaceholder {}
  interface AgcCornHarvestLossResultsPlaceholderAttributes extends StencilHTMLAttributes {}

  interface AgcCornHarvestLossResults {
    'socket': string;
  }
  interface AgcCornHarvestLossResultsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcCornHarvestLoss {
    'mode': "full" | "step";
    'socket': string;
    'tract': string;
    'units': any;
  }
  interface AgcCornHarvestLossAttributes extends StencilHTMLAttributes {
    'mode'?: "full" | "step";
    'onAgcCalculated'?: (event: CustomEvent) => void;
    'onAgcStepChanged'?: (event: CustomEvent) => void;
    'socket'?: string;
    'tract'?: string;
    'units'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AgcCornHarvestLossInputs': Components.AgcCornHarvestLossInputs;
    'AgcCornHarvestLossProgress': Components.AgcCornHarvestLossProgress;
    'AgcCornHarvestLossResultsPlaceholder': Components.AgcCornHarvestLossResultsPlaceholder;
    'AgcCornHarvestLossResults': Components.AgcCornHarvestLossResults;
    'AgcCornHarvestLoss': Components.AgcCornHarvestLoss;
  }

  interface StencilIntrinsicElements {
    'agc-corn-harvest-loss-inputs': Components.AgcCornHarvestLossInputsAttributes;
    'agc-corn-harvest-loss-progress': Components.AgcCornHarvestLossProgressAttributes;
    'agc-corn-harvest-loss-results-placeholder': Components.AgcCornHarvestLossResultsPlaceholderAttributes;
    'agc-corn-harvest-loss-results': Components.AgcCornHarvestLossResultsAttributes;
    'agc-corn-harvest-loss': Components.AgcCornHarvestLossAttributes;
  }


  interface HTMLAgcCornHarvestLossInputsElement extends Components.AgcCornHarvestLossInputs, HTMLStencilElement {}
  var HTMLAgcCornHarvestLossInputsElement: {
    prototype: HTMLAgcCornHarvestLossInputsElement;
    new (): HTMLAgcCornHarvestLossInputsElement;
  };

  interface HTMLAgcCornHarvestLossProgressElement extends Components.AgcCornHarvestLossProgress, HTMLStencilElement {}
  var HTMLAgcCornHarvestLossProgressElement: {
    prototype: HTMLAgcCornHarvestLossProgressElement;
    new (): HTMLAgcCornHarvestLossProgressElement;
  };

  interface HTMLAgcCornHarvestLossResultsPlaceholderElement extends Components.AgcCornHarvestLossResultsPlaceholder, HTMLStencilElement {}
  var HTMLAgcCornHarvestLossResultsPlaceholderElement: {
    prototype: HTMLAgcCornHarvestLossResultsPlaceholderElement;
    new (): HTMLAgcCornHarvestLossResultsPlaceholderElement;
  };

  interface HTMLAgcCornHarvestLossResultsElement extends Components.AgcCornHarvestLossResults, HTMLStencilElement {}
  var HTMLAgcCornHarvestLossResultsElement: {
    prototype: HTMLAgcCornHarvestLossResultsElement;
    new (): HTMLAgcCornHarvestLossResultsElement;
  };

  interface HTMLAgcCornHarvestLossElement extends Components.AgcCornHarvestLoss, HTMLStencilElement {}
  var HTMLAgcCornHarvestLossElement: {
    prototype: HTMLAgcCornHarvestLossElement;
    new (): HTMLAgcCornHarvestLossElement;
  };

  interface HTMLElementTagNameMap {
    'agc-corn-harvest-loss-inputs': HTMLAgcCornHarvestLossInputsElement
    'agc-corn-harvest-loss-progress': HTMLAgcCornHarvestLossProgressElement
    'agc-corn-harvest-loss-results-placeholder': HTMLAgcCornHarvestLossResultsPlaceholderElement
    'agc-corn-harvest-loss-results': HTMLAgcCornHarvestLossResultsElement
    'agc-corn-harvest-loss': HTMLAgcCornHarvestLossElement
  }

  interface ElementTagNameMap {
    'agc-corn-harvest-loss-inputs': HTMLAgcCornHarvestLossInputsElement;
    'agc-corn-harvest-loss-progress': HTMLAgcCornHarvestLossProgressElement;
    'agc-corn-harvest-loss-results-placeholder': HTMLAgcCornHarvestLossResultsPlaceholderElement;
    'agc-corn-harvest-loss-results': HTMLAgcCornHarvestLossResultsElement;
    'agc-corn-harvest-loss': HTMLAgcCornHarvestLossElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
